name: Soia Python Generator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        python-version: ["3.10", "3.11", "3.12"]
        poetry-version: ["latest", "main"]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}
      # From https://github.com/jakebailey/pyright-action
      - run: echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
      - run: npm ci
      - run: npm run format:check
      - run: npm run test
      - uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release
